# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(212522)
$foreground = rgb(F5EAE5)
$color0 = rgb(464B48)
$color1 = rgb(403623)
$color2 = rgb(685F52)
$color3 = rgb(685F52)
$color4 = rgb(685F52)
$color5 = rgb(685F52)
$color6 = rgb(AA9287)
$color7 = rgb(E8D8D1)
$color8 = rgb(A29792)
$color9 = rgb(56482F)
$color10 = rgb(8B7F6E)
$color11 = rgb(8B7F6E)
$color12 = rgb(8B7F6E)
$color13 = rgb(8B7F6E)
$color14 = rgb(E2C2B4)
$color15 = rgb(E8D8D1)
