# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1D1D1D)
$foreground = rgb(EEE6DB)
$color0 = rgb(444344)
$color1 = rgb(1F1C1C)
$color2 = rgb(554B40)
$color3 = rgb(554B40)
$color4 = rgb(897B67)
$color5 = rgb(9A8972)
$color6 = rgb(9A8972)
$color7 = rgb(DED3C3)
$color8 = rgb(9B9388)
$color9 = rgb(2A2626)
$color10 = rgb(716456)
$color11 = rgb(716456)
$color12 = rgb(B7A489)
$color13 = rgb(CEB798)
$color14 = rgb(CEB798)
$color15 = rgb(DED3C3)
