# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

# This is for windowrule of godot engine so that the window of run will be on WINDOW (10)

windowrule = match:title ^(.*\(DEBUG\).*)$, workspace 10 silent
#windowrule = match:title ^(.*\(DEBUG\).*)$, float off

windowrule {
    name = Godot-Debug
    match:class = ^(1st_game)$
    workspace = 10 silent
    tile = on
    center = on
}
