-- Generated by nwg-displays on 2026-05-28 at 16:06:27. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "1600x0",
    scale = 1.2
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@100.0",
    position = "0x0",
    scale = 1.2
})
